import { Classes } from './types';

export default {
  root:                 ['relative', 'select-none'],
  label:                [
    'px-4',
    'py-3',
    'bg-zinc-100',
    'rounded',
    'flex',
    'flex-row',
    'content-center',
    'cursor-pointer',
  ],
  labelTitle:           ['grow', 'font-bold', 'flex', 'items-center'],
  labelCounter:         [
    'bg-emerald-800',
    'text-zinc-100',
    'rounded-full',
    'w-5',
    'h-5',
    'ml-2',
    'inline-flex',
    'items-center',
    'content-center',
  ],
  labelCounterNumber:   [
    'grow', 'text-center', 'text-xs',
  ],
  labelCounterIcon:     ['w-3', 'h-3', 'rounded-full', 'ml-2', 'bg-emerald-800'],
  labelChevronIcon:     ['flex-none', 'w-6', 'transition-transform', 'ml-2'],
  labelChevronIconOpen: ['rotate-180'],
  dropdown:             [
    'absolute',
    'bg-zinc-200',
    'top-full',
    'left-0',
    'right-0',
    'rounded',
    'mt-1',
    'shadow-md',
    'overflow-hidden',
    'z-10',
  ],
  options:              ['divide-y', 'divide-zinc-100'],
  option:               ['px-4', 'py-3', 'flex', 'flex-row', 'cursor-pointer', 'hover:bg-zinc-100'],
  optionLabel:          ['grow'],
  optionIcon:           [
    'w-6',
    'fill-emerald-800',
    'p-0.5',
    'border-2 ',
    'border-emerald-800',
    'rounded',
    'flex-none',
  ],
} as Classes;
